
"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import type { MenuItem, MenuItemCategory, User } from "@/lib/types";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { createClient } from "@/utils/supabase/client";

interface MenuFormDialogProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  onSave: (item: MenuItem) => void;
  item: MenuItem | null;
  user: User;
}

const categories: MenuItemCategory[] = [
  "Adicional", "Bebidas", "Bebidas Quentes", "Caipirinhas", "Cervejas", "Destilados", "Doces", "Lanches", "Porções", "Pratos Quentes", "Saladas", "Salgados", "Sopas", "Sucos"
].sort((a, b) => a.localeCompare(b)) as MenuItemCategory[];


export function MenuFormDialog({ isOpen, onOpenChange, onSave, item, user }: MenuFormDialogProps) {
  const [name, setName] = useState('');
  const [code, setCode] = useState('');
  const [description, setDescription] = useState('');
  const [price, setPrice] = useState('');
  const [category, setCategory] = useState<MenuItemCategory | ''>('');
  const [imageUrl, setImageUrl] = useState('');
  const [stock, setStock] = useState('');
  const [lowStockThreshold, setLowStockThreshold] = useState('');
  const [unit, setUnit] = useState('');

  const { toast } = useToast();
  const supabase = createClient();

  useEffect(() => {
    if (item) {
      setName(item.name);
      setCode(item.code || '');
      setDescription(item.description);
      setPrice(String(item.price));
      setCategory(item.category);
      setImageUrl(item.imageUrl || '');
      setStock(item.stock?.toString() || '');
      setLowStockThreshold(item.lowStockThreshold?.toString() || '');
      setUnit(item.unit || '');
    } else {
        setName('');
        setCode('');
        setDescription('');
        setPrice('');
        setCategory('');
        setImageUrl('');
        setStock('0');
        setLowStockThreshold('0');
        setUnit('un');
    }
  }, [item]);

  const handleImageUpload = async (file: File): Promise<string | null> => {
    if (!user) return null;

    const fileExt = file.name.split('.').pop();
    const fileName = `${user.id}/${Date.now()}.${fileExt}`;
    
    const { data, error } = await supabase.storage
      .from('menu-images')
      .upload(fileName, file);

    if (error) {
      console.error('Error uploading image:', error);
      toast({ variant: 'destructive', title: 'Erro no Upload', description: 'Não foi possível enviar a imagem.'});
      return null;
    }

    const { data: { publicUrl } } = supabase.storage
      .from('menu-images')
      .getPublicUrl(data.path);
      
    return publicUrl;
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.size > 1024 * 1024 * 2) { // 2MB limit
        toast({
            variant: 'destructive',
            title: 'Imagem muito grande',
            description: 'Por favor, selecione uma imagem com menos de 2MB.'
        });
        return;
      }
      
      const uploadedUrl = await handleImageUpload(file);
      if (uploadedUrl) {
          setImageUrl(uploadedUrl);
      }
    }
  };


  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name || !price || !category || !user) return;
    
    const savedItem: MenuItem = {
      id: item?.id || '', // ID will be generated by DB if new
      name,
      code,
      description,
      price: parseFloat(price),
      category,
      imageUrl,
      stock: parseInt(stock, 10) || 0,
      lowStockThreshold: parseInt(lowStockThreshold, 10) || 0,
      unit: unit,
      user_id: user.id
    };
    onSave(savedItem);
  };

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>{item ? 'Editar Item' : 'Adicionar Novo Item'}</DialogTitle>
          <DialogDescription>
            Preencha os detalhes do item do cardápio.
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="grid gap-4 py-4 max-h-[70vh] overflow-y-auto px-2">
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="code" className="text-right">Código</Label>
                <Input id="code" value={code} onChange={e => setCode(e.target.value)} className="col-span-3" />
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="name" className="text-right">Nome</Label>
                <Input id="name" value={name} onChange={e => setName(e.target.value)} className="col-span-3" required />
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="description" className="text-right">Descrição</Label>
                <Textarea id="description" value={description} onChange={e => setDescription(e.target.value)} className="col-span-3" />
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="price" className="text-right">Preço</Label>
                <Input id="price" type="number" step="0.01" value={price} onChange={e => setPrice(e.target.value)} className="col-span-3" required/>
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="category" className="text-right">Categoria</Label>
                <Select value={category} onValueChange={(value) => setCategory(value as MenuItemCategory)} required>
                    <SelectTrigger className="col-span-3">
                        <SelectValue placeholder="Selecione uma categoria" />
                    </SelectTrigger>
                    <SelectContent>
                        {categories.map(cat => (
                            <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                        ))}
                    </SelectContent>
                </Select>
            </div>
             <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="image-upload" className="text-right">Imagem</Label>
                <Input id="image-upload" type="file" accept="image/*" onChange={handleFileChange} className="col-span-3" />
            </div>
            {imageUrl && (
                <div className="grid grid-cols-4 items-center gap-4">
                    <div/>
                    <div className="col-span-3">
                        <Image src={imageUrl} alt="Pré-visualização" width={100} height={100} className="rounded-md object-cover" />
                    </div>
                </div>
            )}
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="stock" className="text-right">Estoque</Label>
                <Input id="stock" type="number" value={stock} onChange={e => setStock(e.target.value)} className="col-span-3" placeholder="Qtd. inicial"/>
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="lowStockThreshold" className="text-right">Alerta Mín.</Label>
                <Input id="lowStockThreshold" type="number" value={lowStockThreshold} onChange={e => setLowStockThreshold(e.target.value)} className="col-span-3" placeholder="Qtd. para alerta"/>
            </div>
             <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="unit" className="text-right">Unidade</Label>
                <Input id="unit" value={unit} onChange={e => setUnit(e.target.value)} className="col-span-3" placeholder="Ex: un, kg, L"/>
            </div>
             <DialogFooter className="mt-4 sticky bottom-0 bg-background py-4">
                <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button>
                <Button type="submit">Salvar</Button>
            </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
